In [ ]:
######## Jupyter notebook to visualize dataset ##########

In [2]:
## Imports

# %matplotlib widget # uncomment for interactive plots
from nlb_tools.nwb_interface import NWBDataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.collections import LineCollection
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [3]:
%ls

X_neural.npy             download.py              train.py
Y_target.npy             model.py                 visualize_dataset.ipynb
__pycache__/             readme.txt
dataset/                 test.nwb


In [4]:
## Load dataset
dataset = NWBDataset("dataset/sub-Indy", "*train", split_heldout=False)

In [5]:
## View 'dataset.data'
dataset.data

signal_type            cursor_pos            finger_pos                        \
channel                         x          y          x          y          z   
clock_time                                                                      
0 days 00:00:00         -4.368126  56.778511  -4.357695  56.758063  94.737781   
0 days 00:00:00.001000  -4.367445  56.776709  -4.356471  56.755696  94.736662   
0 days 00:00:00.002000  -4.366716  56.774849  -4.355222  56.753297  94.735519   
0 days 00:00:00.003000  -4.365940  56.772930  -4.353950  56.750865  94.734355   
0 days 00:00:00.004000  -4.365118  56.770954  -4.352654  56.748402  94.733168   
...                           ...        ...        ...        ...        ...   
0 days 00:10:49.095000  21.912910  21.772385  21.910600  21.775553  87.763974   
0 days 00:10:49.096000  21.912572  21.772658  21.910276  21.775811  87.764095   
0 days 00:10:49.097000  21.912233  21.772935  21.909954  21.776069  87.764220   
0 days 00:10:49.098000  21.911894  21.773216  21.909634  21.776326  87.764350   
0 days 00:10:49.099000  21.911554  21.773500  21.909317  21.776582  87.764485   

signal_type            finger_vel           spikes            ...            \
channel                         x         y    201  203  204  ... 9201 9203   
clock_time                                                    ...             
0 days 00:00:00          1.211079 -2.349968    0.0  0.0  0.0  ...  0.0  0.0   
0 days 00:00:00.001000   1.236134 -2.383193    0.0  0.0  0.0  ...  0.0  0.0   
0 days 00:00:00.002000   1.260579 -2.415633    0.0  0.0  0.0  ...  0.0  0.0   
0 days 00:00:00.003000   1.284410 -2.447283    0.0  0.0  0.0  ...  0.0  0.0   
0 days 00:00:00.004000   1.307626 -2.478143    0.0  0.0  0.0  ...  0.0  0.0   
...                           ...       ...    ...  ...  ...  ...  ...  ...   
0 days 00:10:49.095000  -0.325126  0.258578    0.0  0.0  0.0  ...  0.0  0.0   
0 days 00:10:49.096000  -0.323063  0.258088    0.0  0.0  0.0  ...  0.0  0.0   
0 days 00:10:49.097000  -0.320876  0.257396    0.0  0.0  0.0  ...  0.0  0.0   
0 days 00:10:49.098000  -0.318591  0.256517    0.0  0.0  0.0  ...  0.0  0.0   
0 days 00:10:49.099000  -0.316212  0.255452    0.0  0.0  0.0  ...  0.0  0.0   

signal_type                                          target_pos        
channel                9301 9403 9501 9502 9601 9602          x     y  
clock_time                                                             
0 days 00:00:00         0.0  0.0  0.0  0.0  0.0  0.0       -7.5  52.5  
0 days 00:00:00.001000  0.0  0.0  0.0  0.0  0.0  0.0       -7.5  52.5  
0 days 00:00:00.002000  0.0  0.0  0.0  0.0  0.0  0.0       -7.5  52.5  
0 days 00:00:00.003000  0.0  0.0  0.0  0.0  0.0  0.0       -7.5  52.5  
0 days 00:00:00.004000  0.0  0.0  0.0  0.0  0.0  0.0       -7.5  52.5  
...                     ...  ...  ...  ...  ...  ...        ...   ...  
0 days 00:10:49.095000  0.0  0.0  0.0  0.0  0.0  0.0       37.5  82.5  
0 days 00:10:49.096000  0.0  0.0  0.0  0.0  0.0  0.0       37.5  82.5  
0 days 00:10:49.097000  0.0  0.0  0.0  0.0  0.0  0.0       37.5  82.5  
0 days 00:10:49.098000  0.0  0.0  0.0  0.0  0.0  0.0       37.5  82.5  
0 days 00:10:49.099000  0.0  0.0  0.0  0.0  0.0  0.0       37.5  82.5  

[649100 rows x 139 columns]

In [6]:
dataset.data.iloc[:,15]

clock_time
0 days 00:00:00           0.0
0 days 00:00:00.001000    0.0
0 days 00:00:00.002000    0.0
0 days 00:00:00.003000    0.0
0 days 00:00:00.004000    0.0
                         ... 
0 days 00:10:49.095000    0.0
0 days 00:10:49.096000    0.0
0 days 00:10:49.097000    0.0
0 days 00:10:49.098000    0.0
0 days 00:10:49.099000    0.0
Name: (spikes, 901), Length: 649100, dtype: float16

In [7]:
dataset.data["spikes"]

channel                 201   203   204   301   401   601   701   802   901   \
clock_time                                                                     
0 days 00:00:00          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:00:00.001000   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:00:00.002000   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:00:00.003000   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:00:00.004000   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
...                      ...   ...   ...   ...   ...   ...   ...   ...   ...   
0 days 00:10:49.095000   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:10:49.096000   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:10:49.097000   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:10:49.098000   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:10:49.099000   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

channel                 1001  ...  9001  9103  9201  9203  9301  9403  9501  \
clock_time                    ...                                             
0 days 00:00:00          0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:00:00.001000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:00:00.002000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:00:00.003000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:00:00.004000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
...                      ...  ...   ...   ...   ...   ...   ...   ...   ...   
0 days 00:10:49.095000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:10:49.096000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:10:49.097000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:10:49.098000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
0 days 00:10:49.099000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

channel                 9502  9601  9602  
clock_time                                
0 days 00:00:00          0.0   0.0   0.0  
0 days 00:00:00.001000   0.0   0.0   0.0  
0 days 00:00:00.002000   0.0   0.0   0.0  
0 days 00:00:00.003000   0.0   0.0   0.0  
0 days 00:00:00.004000   0.0   0.0   0.0  
...                      ...   ...   ...  
0 days 00:10:49.095000   0.0   0.0   0.0  
0 days 00:10:49.096000   0.0   0.0   0.0  
0 days 00:10:49.097000   0.0   0.0   0.0  
0 days 00:10:49.098000   0.0   0.0   0.0  
0 days 00:10:49.099000   0.0   0.0   0.0  

[649100 rows x 130 columns]

In [8]:
df_neural_input = dataset.data["spikes"]

In [14]:
# Identifying the NaN locations
nan_locations = df_neural_input.isna()

# Printing the locations of NaN values
for column in nan_locations:
    rows_with_nan = nan_locations[column][nan_locations[column]].index.tolist()
    for row in rows_with_nan:
        print(f"NaN found at Row {row}, Column '{column}'")

NaN found at Row 0 days 00:02:42.200000, Column '201'
NaN found at Row 0 days 00:02:42.201000, Column '201'
NaN found at Row 0 days 00:02:42.202000, Column '201'
NaN found at Row 0 days 00:02:42.203000, Column '201'
NaN found at Row 0 days 00:02:42.204000, Column '201'
NaN found at Row 0 days 00:02:42.205000, Column '201'
NaN found at Row 0 days 00:02:42.206000, Column '201'
NaN found at Row 0 days 00:02:42.207000, Column '201'
NaN found at Row 0 days 00:02:42.208000, Column '201'
NaN found at Row 0 days 00:02:42.209000, Column '201'
NaN found at Row 0 days 00:02:42.210000, Column '201'
NaN found at Row 0 days 00:02:42.211000, Column '201'
NaN found at Row 0 days 00:02:42.212000, Column '201'
NaN found at Row 0 days 00:02:42.213000, Column '201'
NaN found at Row 0 days 00:02:42.214000, Column '201'
NaN found at Row 0 days 00:02:42.215000, Column '201'
NaN found at Row 0 days 00:02:42.216000, Column '201'
NaN found at Row 0 days 00:02:42.217000, Column '201'
NaN found at Row 0 days 00:0

In [9]:
X_neural = df_neural_input.to_numpy()

In [10]:
print(X_neural)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
contains_nan = np.any(np.isnan(X_neural))

In [12]:
print(contains_nan)

True


In [11]:
row_sum_vector = np.sum(X_neural, axis=1)

# Perform column sum
column_sum_vector = np.sum(X_neural, axis=0)

# Display the vectors
print("Row Sum Vector:")
print(row_sum_vector.shape)
print(column_sum_vector.shape)

Row Sum Vector:
(649100,)
(130,)


In [1]:
dataset.data["finger_pos"]

NameError: name 'dataset' is not defined

In [19]:
df_target = dataset.data["finger_pos"]

In [22]:
# Assuming your DataFrame is named df
x_values = df_target['x'].to_numpy()
y_values = df_target['y'].to_numpy()
z_values = df_target['z'].to_numpy()

# Stack 'x' and 'y' arrays vertically
Y_target = np.column_stack((x_values, y_values,z_values))

In [23]:
print(Y_target)

[[-4.35769473 56.75806327 94.73778125]
 [-4.35647098 56.75569649 94.73666161]
 [-4.35522247 56.75329688 94.73551949]
 ...
 [21.90995401 21.77606878 87.76422022]
 [21.90963425 21.77632579 87.76435014]
 [21.90931683 21.77658182 87.76448458]]


In [24]:
# Save the matrices to an npy file
np.save('X_neural.npy', X_neural)
np.save('Y_target.npy', Y_target)

In [25]:
%ls

X_neural.npy             download.py              train.py
Y_target.npy             model.py                 visualize_dataset.ipynb
__pycache__/             readme.txt
dataset/                 test.nwb
