In [2]:
import torch
import matplotlib.pyplot as plt
import numpy as np 
import os
from PIL import Image
import torchvision.transforms as T

In [3]:
# Assuming binary_vector is your binary vector of length 130
binary_vector = torch.randint(0, 2, (130,))  # Example vector, replace with your vector

In [4]:
%ls

X_neural.npy             dataset/                 readme.txt
Y_target.npy             download.py              test.nwb
Z.npy                    evals.py                 train.py
__pycache__/             image_data/              visualize_dataset.ipynb
data_processing.ipynb    model.py
data_processing.py       plot_results.py


In [5]:
Z = np.load('Z.npy')
print(Z)
z_tensor = torch.tensor(Z[805])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
print(Z.shape[0])

649100


In [68]:
# define a transform to convert a tensor to PIL image
transform = T.ToPILImage()

for i in range(Z.shape[0]):
    z_tensor = torch.tensor(Z[i])
    binary_vector = z_tensor*255
    # Create a 64x64 black image
    embedded_image = torch.zeros((64, 64), dtype=torch.float32)
    # Reshape the binary vector (13x10)
    reshaped_vector = binary_vector.view(13, 10)
    # Calculate the starting indices to center the 13x10 tensor
    start_idx_x = (embedded_image.shape[0] - reshaped_vector.shape[0]) // 2
    start_idx_y = (embedded_image.shape[1] - reshaped_vector.shape[1]) // 2
    # Place the reshaped vector into the image
    embedded_image[start_idx_x:start_idx_x + reshaped_vector.shape[0], 
               start_idx_y:start_idx_y + reshaped_vector.shape[1]] = reshaped_vector
    
    # convert the tensor to PIL image using above transform
    img = transform(embedded_image)
    # Specify the folder and filename
    folder_name = 'image_data'
    file_name = f'image_{i}.png'
    path = os.path.join(folder_name, file_name)
    # Ensure the folder exists
    os.makedirs(folder_name, exist_ok=True)
    # Save the image
    img.save(path)
    
    

In [12]:

import numpy as np

# Load the numpy matrix from the .npy file
y_target = np.load('Y_target.npy')

# Check if there are any NaN entries in the matrix
nan_exists = np.isnan(y_target).any()

print("Are there any NaN entries in the matrix?", nan_exists)


Are there any NaN entries in the matrix? False


In [13]:
print(y_target)

[[-4.35769473 56.75806327 94.73778125]
 [-4.35647098 56.75569649 94.73666161]
 [-4.35522247 56.75329688 94.73551949]
 ...
 [21.90995401 21.77606878 87.76422022]
 [21.90963425 21.77632579 87.76435014]
 [21.90931683 21.77658182 87.76448458]]


In [14]:
mean_vector = np.mean(y_target, axis=0)
covariance_matrix = np.cov(y_target, rowvar=False)

print("Mean Vector:")
print(mean_vector)

print("\nCovariance Matrix:")
print(covariance_matrix)

Mean Vector:
[-0.29886825 59.50479278 89.45908063]

Covariance Matrix:
[[794.57038487   6.49999934   8.05755636]
 [  6.49999934 771.36593415   2.3961271 ]
 [  8.05755636   2.3961271   10.02010849]]


In [69]:
val = 0 
i = 0 


In [74]:
for el in y_target:
    diff = el-mean_vector
    val =  val + np.sum(diff**2)
    i = i + 1
    if i == 500000:
        print("here")
        # break

In [75]:
print(val)

1823124317.9354844


In [76]:
print(val/i)

1586.567155108767


In [73]:
500/1600

0.3125

In [8]:
y_target_no_nan = np.nan_to_num(y_target)


In [9]:
nan_exists = np.isnan(y_target_no_nan).any()

print("Are there any NaN entries in the matrix?", nan_exists)

Are there any NaN entries in the matrix? False


In [10]:
np.save('Y_target.npy', y_target_no_nan)

In [65]:


print(f"Image saved to {path}")

Image saved to image_data/my_image.png


In [55]:
# Ensure the 'image_data' folder exists
os.makedirs('image_data', exist_ok=True)

# Save the image to the 'image_data' folder
plt.savefig('image_data/centered_binary_vector.png')


<Figure size 640x480 with 0 Axes>